# config/routes.yaml
home:
    path: /
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\BristolController::home
#add:
#   path: /add
#   controller: App\Controller\BookingController::add
